# Generated by Django 4.1.4 on 2022-12-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('formacion', models.DateField()),
                ('desintegracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('instrumento', models.CharField(max_length=45)),
                ('lugar_nacimiento', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_muerte', models.DateField()),
            ],
        ),
    ]
