# Generated by Django 4.1.4 on 2022-12-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupos',
        ),
        migrations.DeleteModel(
            name='Musico',
        ),
    ]
