# Generated by Django 4.1.4 on 2022-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_delete_grupos_delete_musico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('formacion', models.DateField()),
                ('desintegracion', models.DateField()),
            ],
        ),
    ]
