# Generated by Django 4.1.4 on 2022-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('instrumento', models.CharField(max_length=45)),
                ('lugar_nacimiento', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_muerte', models.DateField()),
            ],
        ),
    ]
