# Generated by Django 4.1.4 on 2022-12-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_musico'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerosGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musica.genero')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musica.grupos')),
            ],
        ),
    ]
