# Generated by Django 4.1.4 on 2022-12-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_generosgrupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicosGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musica.grupos')),
                ('musicos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musica.musico')),
            ],
        ),
    ]
