# Generated by Django 4.1.4 on 2022-12-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_musicosgrupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='genero',
            field=models.ManyToManyField(through='musica.GenerosGrupos', to='musica.genero'),
        ),
    ]
